version: '{build}'
os: Visual Studio 2017
branches:
    only:
        - master
init:
 - cmd: dotnet --version
before_build:
 - cmd: dotnet restore ./src/CAESAR.Chess/CAESAR.Chess.csproj --verbosity m
build_script:
 - cmd: dotnet publish ./src/CAESAR.Chess/CAESAR.Chess.csproj
test_script:
 - cmd: dotnet restore ./tests/CAESAR.Chess.Tests/CAESAR.Chess.Tests.csproj --verbosity m
 - cmd: cd tests
 - cmd: cd CAESAR.Chess.Tests
 - cmd: dotnet test