version: '{build}'
os: Visual Studio 2015
init:
 - cmd: set PATH=C:\Python34-x64;C:\Python34-x64\Scripts;%PATH%
install:
 - ps: Start-FileDownload https://raw.github.com/pypa/pip/master/contrib/get-pip.py
 - cmd: python get-pip.py
 - cmd: nuget sources add -Name api.nuget.org -Source https://api.nuget.org/v3/index.json
 - ps: "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
 - ps: dnvm update-self
 - ps: dnvm upgrade
 - ps: dnvm install 1.0.0-rc1-update1
 - ps: dnvm list
 - ps: dnvm use 1.0.0-rc1-update1
before_build:
 - ps: dnu restore
build_script:
 - cmd: pip install codecov
test_script:
 - cmd: cd c:\projects\caesar\src\CAESAR.Chess
 - cmd: dnu build
 - cmd: cd c:\projects\caesar\tests\CAESAR.Chess.Tests
 - cmd: C:\Users\appveyor\.dnx\packages\OpenCover\4.6.261-rc\tools\OpenCover.Console.exe -target:"C:\Users\appveyor\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin\dnx.exe" -targetargs:"--lib c:\projects\caesar\src\CAESAR.Chess\bin\Debug\dnx451 test" -output:"c:\projects\caesar\CAESAR_coverage.xml" -returntargetcode -register:Path32 -hideskipped:All -filter:"+[CAESAR*]* -[*Tests]*"
 - cmd: cd c:\projects\caesar
 - cmd: codecov -f "CAESAR_coverage.xml" -X gcov
