using System.Collections.Generic;
using CAESAR.Chess.PlayArea;

namespace CAESAR.Chess.Moves.Generation
{
    /// <summary>
    ///     Generates <seealso cref="IMove" />s for a particular <seealso cref="ISquare" />, based on a particular set of move
    ///     generation rules.
    /// </summary>
    public interface IMovesGenerator
    {
        /// <summary>
        ///     The <seealso cref="IMove" />s generated by this <seealso cref="IMovesGenerator" />.
        /// </summary>
        IEnumerable<IMove> Moves { get; }

        /// <summary>
        ///     The <seealso cref="ISquare" />s that can be used to generate <seealso cref="CapturingMove" />s by this
        ///     <seealso cref="IMovesGenerator" />.
        /// </summary>
        IEnumerable<ISquare> CaptureSquares { get; }

        /// <summary>
        ///     The <seealso cref="ISquare" /> of the <seealso cref="IMovesGenerator" />.
        /// </summary>
        ISquare Square { get; set; }
    }
}