using System.Collections.Generic;
using System.Linq;
using CAESAR.Chess.Core;
using CAESAR.Chess.Pieces;
using CAESAR.Chess.PlayArea;

namespace CAESAR.Chess.Moves.Generation
{
    /// <summary>
    ///     Generates <seealso cref="IMove" />s for a particular <seealso cref="ISquare" />, based on a particular set of move
    ///     generation rules.
    /// </summary>
    public abstract class MovesGenerator : IMovesGenerator
    {
        private IEnumerable<NormalMove> MovementMoves => MovementSquares.Distinct()
            .Where(square => square != null && square.Piece == null)
            .Select(square => new NormalMove(Square, square.Name));

        private IEnumerable<CapturingMove> Captures => CaptureSquares.Distinct()
            .Where(square => square?.Piece != null && square.Piece.Side != Piece.Side)
            .Select(square => new CapturingMove(Square, square.Name));

        protected abstract IEnumerable<IMove> SpecialMoves { get; }
        protected abstract IEnumerable<ISquare> MovementSquares { get; }
        protected abstract IEnumerable<ISquare> CaptureSquares { get; }

        protected IPiece Piece => Square?.Piece;
        protected Side Side => Piece.Side;

        /// <summary>
        ///     The <seealso cref="IMove" />s generated by this <seealso cref="IMovesGenerator" />. It is made up of
        ///     <seealso cref="NormalMove" />s, <seealso cref="CapturingMove" />s, and various <seealso cref="SpecialMoves" />.
        /// </summary>
        public IEnumerable<IMove> Moves
            => Piece != null ? MovementMoves.Concat(Captures).Concat(SpecialMoves) : Enumerable.Empty<IMove>();


        /// <summary>
        ///     The <seealso cref="ISquare" /> of the <seealso cref="IMovesGenerator" />.
        /// </summary>
        public ISquare Square { get; set; }
    }
}